// <auto-generated />
namespace Alexa_GWV.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserPreferences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserPreferences));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281523071_UserPreferences"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
